Add support for multiple DNS zones

diff --git a/ddns-cloudflare b/ddns-cloudflare
--- a/ddns-cloudflare
+++ b/ddns-cloudflare
@@ -6,16 +6,21 @@
 #
 # Yu Shiyang <yu.shiyang@gnayihs.uy>
 
-# List of domains to update is given in /etc/opt/ddns-cloudflare/domains in this format:
+# Each DNS zone should have its own subdirectory in /etc/opt/ddns-cloudflare/
+#   e.g. /etc/opt/ddns-cloudflare/example.com/
+#
+# The list of domains to update is given in /etc/opt/ddns-cloudflare/<zone>/domains in this format:
 #   domains='example.com', 'subdomain.example.com', '*.wildcard.example.com'
 #
-# Authentication information for Cloudflare is given in /etc/opt/ddns-cloudflare/auth in this format:
-#   zoneid=zoneid
-#   authtoken=authtoken
+# Authentication information for Cloudflare is given in /etc/opt/ddns-cloudflare/<zone>/auth in this format:
+#   zoneid=<zoneid>
+#   authtoken=<authtoken>
 #
-# Values may optionally be enclosed in single or double quotes
+# Values may optionally be enclosed in single or double quotes, or no quotes
 
 name="ddns-cloudflare"
+
+config_dir='/etc/opt/ddns-cloudflare'
 
 help="Usage: $name [-qh] [<options>]"
 help="$help\n"
@@ -102,15 +107,6 @@ if [ -n "$warn_after" ]; then
 fi
 
 
-config_dir='/etc/opt/ddns-cloudflare'
-
-# auth
-zoneid="$( sed -n "s/^\s*zoneid\s*=\s*\(.\+\)/\1/p" "$config_dir/auth" | xargs -n 1 )"
-authtoken="$( sed -n "s/^\s*authtoken\s*=\s*\(.\+\)/\1/p" "$config_dir/auth" | xargs -n 1 )"
-# domains
-IFS=$'\n' names=( $( sed -n "s/^\s*domains\s*=\s*\(.\+\)/\1/p" "$config_dir/domains" | xargs -d ',' -n 1 | xargs -l ) )
-
-
 publicip="$( curl -s https://ifconfig.me/ip )"
 
 if [ -z "$publicip" ]; then
@@ -136,8 +132,15 @@ else
 fi
 
 
+# Renew certs for the default config in $config_dir (for backwards compatibility)
 error=0
 delayed_print_error=0
+
+# auth
+zoneid="$( sed -n "s/^\s*zoneid\s*=\s*\(.\+\)/\1/p" "$config_dir/auth" | xargs -n 1 )"
+authtoken="$( sed -n "s/^\s*authtoken\s*=\s*\(.\+\)/\1/p" "$config_dir/auth" | xargs -n 1 )"
+# domains
+IFS=$'\n' names=( $( sed -n "s/^\s*domains\s*=\s*\(.\+\)/\1/p" "$config_dir/domains" | xargs -d ',' -n 1 | xargs -l ) )
 
 for i in "${names[@]}"; do
 	response="$( curl -s -X GET 'https://api.cloudflare.com/client/v4/zones/'"$zoneid"'/dns_records?type=A&name='"${i}" -H 'Content-Type:application/json' -H 'Authorization: Bearer '"$authtoken" )"
@@ -160,12 +163,12 @@ for i in "${names[@]}"; do
 				echo -e "\e[31m$code: \e[97m${i}\e[31m failed to update\e[39m"
 			fi
 			if [ -z "$warn_threshold" ]; then
-				echo -n "$name: " >& 2
+				echo -n "$name: (default): " >& 2
 				cat /tmp/ddns-cloudflare.response >& 2
 			else
 				if [ -f /tmp/ddns-cloudflare.first-error ]; then
 					if [ $warn_threshold -gt $(cat /tmp/ddns-cloudflare.first-error) ]; then
-						echo -n "$name: " >& 2
+						echo -n "$name: (default): " >& 2
 						cat /tmp/ddns-cloudflare.response >& 2
 						echo "" >& 2
 						delayed_print_error=1
@@ -184,7 +187,7 @@ for i in "${names[@]}"; do
 done
 
 if [ $delayed_print_error -ne 0 ]; then
-	echo "$name: failing since $(date -d @"$(cat /tmp/ddns-cloudflare.first-error)" -R)" >& 2
+	echo "$name: (default): failing since $(date -d @"$(cat /tmp/ddns-cloudflare.first-error)" -R)" >& 2
 	rm /tmp/ddns-cloudflare.first-error
 fi
 if [ $error -ne 0 ]; then
@@ -194,3 +197,77 @@ else
 		rm /tmp/ddns-cloudflare.first-error
 	fi
 fi
+
+
+
+# Renew certs for each config in a subdirectory of $config_dir
+for subconfig_dir in "$config_dir"/*; do
+	if [ -d "$subconfig_dir" ]; then
+		error=0
+		delayed_print_error=0
+
+		subconfig_name="$(basename "$subconfig_dir")"
+
+		# auth
+		zoneid="$( sed -n "s/^\s*zoneid\s*=\s*\(.\+\)/\1/p" "$subconfig_dir/auth" | xargs -n 1 )"
+		authtoken="$( sed -n "s/^\s*authtoken\s*=\s*\(.\+\)/\1/p" "$subconfig_dir/auth" | xargs -n 1 )"
+		# domains
+		IFS=$'\n' names=( $( sed -n "s/^\s*domains\s*=\s*\(.\+\)/\1/p" "$subconfig_dir/domains" | xargs -d ',' -n 1 | xargs -l ) )
+
+		for i in "${names[@]}"; do
+			response="$( curl -s -X GET 'https://api.cloudflare.com/client/v4/zones/'"$zoneid"'/dns_records?type=A&name='"${i}" -H 'Content-Type:application/json' -H 'Authorization: Bearer '"$authtoken" )"
+			recordip="$( echo "$response" | jq -Mr '.result[0].content' )"
+			if [ "$recordip" != "$publicip" ]; then
+				recordid="$( echo "$response" | jq -Mr '.result[0].id' )"
+				recordttl="$( echo "$response" | jq -Mr '.result[0].ttl' )"
+				recordproxied="$( echo "$response" | jq -Mr '.result[0].proxied' )"
+				code="$( curl -s -o /tmp/ddns-cloudflare.response -w '%{http_code}' -X PUT 'https://api.cloudflare.com/client/v4/zones/'"$zoneid"'/dns_records/'"$recordid" -H 'Content-Type:application/json' -H 'Authorization: Bearer '"$authtoken" --data '{"type":"A","name":"'"${i}"'","content":"'"$publicip"'","ttl":'"$recordttl"',"proxied":'"$recordproxied"'}' )"
+				if [ "$code" == 200 ]; then
+					if [ $quiet -le 1 ]; then
+						echo -e "200: \e[97m${i}\e[39m updated to $publicip"
+					fi
+					if [ -f /tmp/ddns-cloudflare.first-error ]; then
+						rm /tmp/ddns-cloudflare.first-error
+					fi
+				else
+					error=1
+					if [ $quiet -le 1 ]; then
+						echo -e "\e[31m$code: \e[97m${i}\e[31m failed to update\e[39m"
+					fi
+					if [ -z "$warn_threshold" ]; then
+						echo -n "$name: $subconfig_name:" >& 2
+						cat /tmp/ddns-cloudflare.response >& 2
+					else
+						if [ -f /tmp/ddns-cloudflare.first-error ]; then
+							if [ $warn_threshold -gt $(cat /tmp/ddns-cloudflare.first-error) ]; then
+								echo -n "$name: $subconfig_name:" >& 2
+								cat /tmp/ddns-cloudflare.response >& 2
+								echo "" >& 2
+								delayed_print_error=1
+							fi
+						else
+							date +%s > /tmp/ddns-cloudflare.first-error
+						fi
+					fi
+				fi
+				rm /tmp/ddns-cloudflare.response
+			else
+				if [ $quiet -le 0 ]; then
+					echo -e "\e[97m${i}\e[39m unchanged; skipped"
+				fi
+			fi
+		done
+
+		if [ $delayed_print_error -ne 0 ]; then
+			echo "$name: $subconfig_name: failing since $(date -d @"$(cat /tmp/ddns-cloudflare.first-error)" -R)" >& 2
+			rm /tmp/ddns-cloudflare.first-error
+		fi
+		if [ $error -ne 0 ]; then
+			exit $error
+		else
+			if [ -f /tmp/ddns-cloudflare.first-error ]; then
+				rm /tmp/ddns-cloudflare.first-error
+			fi
+		fi
+	fi
+done
