Reduce sensitivity to DNS update errors

diff --git a/ddns-cloudflare b/ddns-cloudflare
--- a/ddns-cloudflare
+++ b/ddns-cloudflare
@@ -15,15 +15,20 @@
 #
 # Values may optionally be enclosed in single or double quotes
 
+name="ddns-cloudflare"
+
 help="Usage: ddns-cloudflare [-qh] [options]\n"
 help="$help\nOptions:"
 help="$help\n  -q, --quiet     Use once to disable printing unchanged domains to stdout"
 help="$help\n                  Use twice to disable printing all status to stdout status"
 help="$help\n                  Error messages will always be printed to stderr"
+help="$help\n  -w <time>, --warn=<time>, --warn-after=<time>"
+help="$help\n                  Do not print to stderr for DNS update failures unless it has failed consistently for the period of <time>"
 help="$help\n  -h, -?, --help  Display this help message and exit"
-quiet=0
 
-name="$0"
+quiet=0
+warnafter=
+
 while [ $# -gt 0 ]; do
 	case "$1" in
 		--help)
@@ -31,19 +36,51 @@ while [ $# -gt 0 ]; do
 			exit 0
 			;;
 		--quiet) ((++quiet)) ;;
+		--warn*)
+			case "$1" in
+				*=*) warnafter="${1#*=}" ;;
+				*)
+					case "$2" in
+						-*) ;;
+						*)
+							warnafter="$2"
+							shift
+					esac
+			esac
+			if [ -z "$warnafter" ]; then
+				echo "$name: missing required argument for option '$1'" >& 2
+				exit 2
+			fi
+			;;
 		--*)
 			echo "$name: invalid option '$1'" >& 2
 			exit 2
 			;;
 		-*)
-			flags=( $(echo "${1:1}" | grep -o .) )
-			for flag in "${flags[@]}"; do
+			for i in $(seq 1 $((${#1} - 1))); do
+				flag="${1:$i:1}"
 				case "$flag" in
 					h|\?)
 						echo -e "$help"
 						exit 0
 						;;
 					q) ((++quiet)) ;;
+					w)
+						warnafter="${1:$((i + 1))}"
+						if [ -z "$warnafter" ]; then
+							case "$2" in
+								-*) ;;
+								*)
+									warnafter="$2"
+									shift
+							esac
+						fi
+						if [ -z "$warnafter" ]; then
+							echo "$name: missing required argument for option '$flag'" >& 2
+							exit 2
+						fi
+						break
+						;;
 					*)
 						echo "$name: invalid option '$flag'" >& 2
 						exit 2
@@ -82,16 +119,32 @@ for i in "${names[@]}"; do
 		recordttl="$( echo "$response" | jq -Mr '.result[0].ttl' )"
 		recordproxied="$( echo "$response" | jq -Mr '.result[0].proxied' )"
 		code="$( curl -s -o /tmp/ddns-cloudflare.response -w '%{http_code}' -X PUT 'https://api.cloudflare.com/client/v4/zones/'"$zoneid"'/dns_records/'"$recordid" -H 'Content-Type:application/json' -H 'Authorization: Bearer '"$authtoken" --data '{"type":"A","name":"'"${i}"'","content":"'"$publicip"'","ttl":'"$recordttl"',"proxied":'"$recordproxied"'}' )"
+		code=1
 		if [ "$code" == 200 ]; then
 			if [ $quiet -le 1 ]; then
 				echo -e "200: \e[97m${i}\e[39m updated to $publicip"
+			fi
+			if [ -f /tmp/ddns-cloudflare.first-error ]; then
+				rm /tmp/ddns-cloudflare.first-error
 			fi
 		else
 			if [ $quiet -le 1 ]; then
 				echo -e "\e[31m$code: \e[97m${i}\e[31m failed to update\e[39m"
 			fi
-			echo -n "$name: " >& 2
-			cat /tmp/ddns-cloudflare.response >& 2
+			if [ -z "$warnafter" ]; then
+				echo -n "$name: " >& 2
+				cat /tmp/ddns-cloudflare.response >& 2
+			else
+				if [ -f /tmp/ddns-cloudflare.first-error ]; then
+					if [ $(date -d -"$warnafter" +%s) -gt $(cat /tmp/ddns-cloudflare.first-error) ]; then
+						echo -n "$name: " >& 2
+						cat /tmp/ddns-cloudflare.response >& 2
+						echo "$name: failing since $(date -d -"$warnafter" -R)" >& 2
+					fi
+				else
+					date +%s > /tmp/ddns-cloudflare.first-error
+				fi
+			fi
 			error=1
 		fi
 		rm /tmp/ddns-cloudflare.response
